// Generated by CoffeeScript 1.7.1
(function() {
  var corsController, myApp;

  myApp = angular.module("CorsApp", []);

  corsController = function($scope, $http) {
    return $http.get("http://localhost:4000/").success(function(data, status, headers, config) {
      console.log("Success: ", data);
      return $scope.message = data.message;
    }).error(function(data, status, headers, config) {
      return console.log("Error: ", data);
    });
  };

  myApp.controller('corsController', corsController);

}).call(this);

//# sourceMappingURL=corsController.map
